### ISSUE TITLE
Move from OAuth 1.0a to OAuth 2.0 for OSM logins

### ISSUE THREAD

**Issue by mmd-osm** [geofabrik/sendfile_osm_oauth_protector#10]
OSM's OAuth 1.0a is in the process of being deprecated, as discussed at https://github.com/openstreetmap/operations/issues/867. No timeline has been set, but we do not expect to shut off OAuth 1.0a this year. It would be good to move to OAuth 2.0 well before this time.

**Comment by danieldegroot2** [comment]
Note, `api.openstreetmap.org` API url currently can not do OAuth 2 handshake. See https://github.com/openstreetmap/operations/issues/951#issuecomment-1748717154
You can split the `www.` base URL and `api.` API url. See https://github.com/osmlab/osm-auth/pull/123#issuecomment-1777330094

**Comment by mmd-osm** [comment]
Update on schedule: https://github.com/openstreetmap/operations/issues/867#issuecomment-1888114871:

The schedule proposed at the meeting today was starting on March 1st stop new OAuth 1.0a registrations, May 1st start brownouts to alert anyone who has not gotten the message, and **shut off OAuth 1.0a and HTTP basic auth on June 1st.**

**Comment by tyrasd** [comment]
As a sidenote: https://github.com/OpenIDC/mod_auth_openidc can be used to get a behaviour as this  effect as this repo and can be configured to work with OAuth2.
