### ISSUE TITLE
The oauth_cookie_client.py fails

### ISSUE THREAD

**Issue by JitGub** [geofabrik/sendfile_osm_oauth_protector#9]
The oauth_cookie_client.py fails

In oauth_cookie_client.py line 97 change "yes" to "1".
Necessary after after change on OSM server side.

See also:
https://github.com/openstreetmap/openstreetmap-website/pull/3177
https://github.com/openstreetmap/openstreetmap-website/issues/3241

**Comment by flacombe** [comment]
I confirm this cause issues in several projects.

Would a PR be useful to fix ?

**Comment by JitGub** [comment]
No longer relevant after shift to OAuth 2.0
